soc/amd/cmn/block/spi/backup_boot_device_rw_nommap.c: Fix format string
clang complains:
error: format specifies type 'long' but the argument has type 'size_t' (aka 'unsigned int') [-Werror,-Wformat]
  188 |         printk(BIOS_INFO, "%s: Synced %ld bytes from SPI flash %s->%s\n", __func__,
      |                                       ~~~
      |                                       %zu
  189 |                written, direction_prim_to_sec ? "PRIM" : "SEC",
      |                ^~~~~~~
1 error generated.

Interestingly GCC doesn't complain, which is probably why that issue
wasn't caught earlier.

Signed-off-by: Maximilian Brune <maximilian.brune@9elements.com>
Change-Id: I2a1c39a9031b328456fa3b2f6fff8b4545f18cf2
Reviewed-on: https://review.coreboot.org/c/coreboot/+/92589
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Felix Held <felix-coreboot@felixheld.de>